window.env = {
  "npm_package_dependencies__popmotion_popcorn": "^0.4.4",
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/v.litvinov/Desktop/Portfolio/Portfolio",
  "npm_package_homepage": "https://gostop93.github.io/Litvinov_Mikhail_Frontend_Developer",
  "npm_config_version_git_tag": "true",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "npm_package_dependencies_react_dotenv": "^0.1.3",
  "TMPDIR": "/var/folders/01/mg09csrn6zv9nf5pkt4sbt4w0000gp/T/",
  "npm_package_dependencies__emailjs_browser": "^4.3.3",
  "npm_config_init_license": "MIT",
  "TERM_PROGRAM_VERSION": "1.94.2",
  "npm_package_dependencies_tsparticles": "^3.3.0",
  "MallocNanoZone": "0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "ZDOTDIR": "/Users/v.litvinov",
  "npm_package_dependencies_react_fast_marquee": "^1.6.4",
  "npm_package_private": "true",
  "npm_config_registry": "https://registry.yarnpkg.com",
  "npm_package_dependencies_react_dom": "^18.2.0",
  "npm_package_readmeFilename": "README.md",
  "USER": "v.litvinov",
  "npm_package_description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
  "npm_package_dependencies_web_vitals": "^2.1.4",
  "npm_package_devDependencies__types_react": "^18.2.31",
  "COMMAND_MODE": "unix2003",
  "npm_package_scripts_deploy": "gh-pages -d build",
  "npm_package_dependencies__testing_library_user_event": "^13.5.0",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.Y5601IM1Wm/Listeners",
  "npm_package_dependencies_zustand": "^4.5.2",
  "npm_package_dependencies_react_helmet": "^6.1.0",
  "__CF_USER_TEXT_ENCODING": "0x1F6:0x0:0x0",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_package_dependencies_styled_components": "^6.1.0",
  "npm_execpath": "/usr/local/lib/node_modules/yarn/bin/yarn.js",
  "npm_package_scripts_predeploy": "npm run build",
  "npm_package_dependencies_react_awesome_button": "^7.0.5",
  "npm_package_dependencies_react_particles": "^2.12.2",
  "npm_package_devDependencies__types_react_dom": "^18.2.14",
  "PATH": "/var/folders/01/mg09csrn6zv9nf5pkt4sbt4w0000gp/T/yarn--1749588699358-0.31520289730825013:/Users/v.litvinov/Desktop/Portfolio/Portfolio/node_modules/.bin:/Users/v.litvinov/.config/yarn/link/node_modules/.bin:/usr/local/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/mysql-9.2.0-macos15-arm64/bin:/usr/local/mysql-9.2.0-macos15-arm64/bin:/usr/local/mysql-9.2.0-macos15-arm64/bin:/usr/local/mysql-9.2.0-macos15-arm64/bin:/Users/v.litvinov/.yarn/bin:/Users/v.litvinov/.config/yarn/global/node_modules/.bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/mysql-9.2.0-macos15-arm64/bin:/Users/v.litvinov/.yarn/bin:/Users/v.litvinov/.config/yarn/global/node_modules/.bin",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"build\"],\"original\":[\"build\"]}",
  "LaunchInstanceID": "5DAD5335-C92E-4342-80F9-9D3B0D373DD6",
  "_": "/Users/v.litvinov/Desktop/Portfolio/Portfolio/node_modules/.bin/react-dotenv",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "USER_ZDOTDIR": "/Users/v.litvinov",
  "npm_package_browserslist_production_1": "not dead",
  "npm_package_dependencies_typescript": "^4.9.5",
  "npm_package_dependencies_react_toastify": "^9.1.3",
  "npm_package_dependencies__types_jest": "^27.5.2",
  "PWD": "/Users/v.litvinov/Desktop/Portfolio/Portfolio",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_dependencies__gsap_react": "^2.1.0",
  "npm_lifecycle_event": "build",
  "npm_package_browserslist_production_2": "not op_mini all",
  "LANG": "en_US.UTF-8",
  "npm_package_name": "portfolio",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_config_version_commit_hooks": "true",
  "XPC_FLAGS": "0x0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "",
  "npm_package_dependencies_react_router_dom": "^6.17.0",
  "npm_package_dependencies_react_flip_toolkit": "^7.1.0",
  "npm_package_dependencies__tsparticles_react": "^3.0.0",
  "npm_config_bin_links": "true",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "VSCODE_INJECTION": "1",
  "HOME": "/Users/v.litvinov",
  "SHLVL": "2",
  "VSCODE_GIT_ASKPASS_MAIN": "/private/var/folders/01/mg09csrn6zv9nf5pkt4sbt4w0000gp/T/AppTranslocation/3FB7B506-97A7-4D95-9984-A512277E4388/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "npm_package_scripts_test": "react-scripts test",
  "npm_package_dependencies__studio_freight_react_lenis": "^0.0.46",
  "npm_package_dependencies_framer_motion": "^11.0.25",
  "npm_package_dependencies_formik": "^2.4.5",
  "npm_config_save_prefix": "^",
  "npm_config_strict_ssl": "true",
  "npm_package_dependencies__testing_library_jest_dom": "^5.17.0",
  "npm_config_version_git_message": "v%s",
  "npm_package_dependencies__types_node": "^16.18.59",
  "LOGNAME": "v.litvinov",
  "YARN_WRAP_OUTPUT": "false",
  "npm_package_dependencies_react_scripts": "5.0.1",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_package_devDependencies_gh_pages": "^6.1.1",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/01/mg09csrn6zv9nf5pkt4sbt4w0000gp/T/vscode-git-52b168ba94.sock",
  "npm_package_dependencies_yup": "^1.4.0",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_dependencies_react": "^18.2.0",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_dependencies__testing_library_react": "^13.4.0",
  "npm_config_version_git_sign": "",
  "npm_config_ignore_scripts": "",
  "npm_config_user_agent": "yarn/1.22.22 npm/? node/v20.18.0 darwin arm64",
  "GIT_ASKPASS": "/private/var/folders/01/mg09csrn6zv9nf5pkt4sbt4w0000gp/T/AppTranslocation/3FB7B506-97A7-4D95-9984-A512277E4388/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/private/var/folders/01/mg09csrn6zv9nf5pkt4sbt4w0000gp/T/AppTranslocation/3FB7B506-97A7-4D95-9984-A512277E4388/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "npm_package_dependencies_tsparticles_slim": "^2.12.0",
  "npm_package_devDependencies__types_react_helmet": "^6.1.11",
  "npm_config_init_version": "1.0.0",
  "npm_config_ignore_optional": "",
  "SECURITYSESSIONID": "186a2",
  "npm_package_scripts_eject": "react-scripts eject",
  "NODE_EXTRA_CA_CERTS": "/Users/v.litvinov/Desktop/certificate.pem",
  "COLORTERM": "truecolor",
  "npm_node_execpath": "/usr/local/bin/node",
  "npm_config_version_tag_prefix": "v",
  "EMAILJS_PUBLIC_KEY": "8tCp4YJqlpfdZkY0H",
  "EMAILJS_TEMPLATE_ID": "template_90xckmk",
  "EMAILJS_SERVICE_ID": "service_io2bj9o",
  "PHONE_NUMBER": "48508832664"
};